### ISSUE TITLE
Sensor for slicer remaining time

### ISSUE THREAD

**Issue by alexspeller** [Lyr3x/hass-Duet3D#29]
The `time_remaining` sensor seems to only pull from the File Progress estimated time remaining

<img width="1013" alt="Image" src="https://github.com/user-attachments/assets/322a83e1-5b7c-4631-800f-8480358d71ca" />

Unfortunately, for me this number is so inaccurate as to be useless; It swings by a factor of 10 over the course of the print:

<img width="318" alt="Image" src="https://github.com/user-attachments/assets/981a51d2-ff97-42ae-ab92-f813c3f03ad7" />

Is there any way to get the slicer remaining time figure as a sensor? That one is way more accurate usually.

Thanks!

**Comment by alexspeller** [comment]
If anyone comes across this on google, I manage to make my own with a command line sensor

```
command_line:
  - sensor:
      name: "Printer Seconds Left"
      command: curl -s "http://printer.local/rr_model?key=job.timesLeft.slicer"
      command_timeout: 10
      value_template: "{{ value_json.result }}"
      scan_interval: 120
      unit_of_measurement: "s"
      unique_id: printer_slicer_seconds_left

```
